program test_dlanv2
  use test_utils
  implicit none
  double precision :: a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn

  ! Test 1: C=0, already in Schur form
  a = 1.0d0; b = 2.0d0; c = 0.0d0; d = 3.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('c_zero')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 2: B=0, swap rows and columns
  a = 3.0d0; b = 0.0d0; c = 4.0d0; d = 1.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('b_zero')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 3: A=D and sign(B) != sign(C), already Schur form
  a = 2.0d0; b = 3.0d0; c = -1.0d0; d = 2.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('a_eq_d_diff_sign')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 4: Real eigenvalues (Z >= MULTPL*EPS)
  a = 4.0d0; b = 1.0d0; c = 2.0d0; d = 3.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('real_eigenvalues')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 5: Complex conjugate eigenvalues
  a = 1.0d0; b = -5.0d0; c = 1.0d0; d = 1.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('complex_eigenvalues')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 6: Zero matrix
  a = 0.0d0; b = 0.0d0; c = 0.0d0; d = 0.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('zero_matrix')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 7: Identity matrix
  a = 1.0d0; b = 0.0d0; c = 0.0d0; d = 1.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('identity')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 8: Diagonal, distinct eigenvalues
  a = 5.0d0; b = 0.0d0; c = 0.0d0; d = 2.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('diagonal')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 9: Real eigenvalues with negative entries
  a = -1.0d0; b = 3.0d0; c = 2.0d0; d = 4.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('real_negative')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 10: Complex eigenvalues, equal diag, B*C<0
  a = 3.0d0; b = -4.0d0; c = 2.0d0; d = 3.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('complex_equal_diag')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 11: Near-equal eigenvalues (small Z)
  a = 1.0d0; b = 1.0d-15; c = 1.0d-15; d = 1.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('near_equal')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 12: Large values
  a = 1.0d150; b = 2.0d150; c = 3.0d150; d = 4.0d150
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('large_values')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 13: Complex eigenvalues path with sign(B) == sign(C) (real reduction sub-path)
  a = 2.0d0; b = 3.0d0; c = 3.0d0; d = 2.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('same_sign_bc')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

  ! Test 14: B=0, C!=0 triggers the ELSE (B==-C, swap CS/SN)
  a = 2.0d0; b = 1.0d-16; c = 1.0d-16; d = 2.0d0
  call dlanv2(a, b, c, d, rt1r, rt1i, rt2r, rt2i, cs, sn)
  call begin_test('tiny_bc')
  call print_scalar('a', a)
  call print_scalar('b', b)
  call print_scalar('c', c)
  call print_scalar('d', d)
  call print_scalar('rt1r', rt1r)
  call print_scalar('rt1i', rt1i)
  call print_scalar('rt2r', rt2r)
  call print_scalar('rt2i', rt2i)
  call print_scalar('cs', cs)
  call print_scalar('sn', sn)
  call end_test()

end program
