program test_zlaev2
  use test_utils
  implicit none
  complex*16 :: a, b, c, sn1
  double precision :: rt1, rt2, cs1

  ! Test 1: Real diagonal matrix (b=0), a > c
  a = dcmplx(3.0d0, 0.0d0)
  b = dcmplx(0.0d0, 0.0d0)
  c = dcmplx(1.0d0, 0.0d0)
  call zlaev2(a, b, c, rt1, rt2, cs1, sn1)
  call begin_test('real_diagonal')
  call print_scalar('ar', dble(a))
  call print_scalar('ai', dimag(a))
  call print_scalar('br', dble(b))
  call print_scalar('bi', dimag(b))
  call print_scalar('cr', dble(c))
  call print_scalar('ci', dimag(c))
  call print_scalar('rt1', rt1)
  call print_scalar('rt2', rt2)
  call print_scalar('cs1', cs1)
  call print_scalar('sn1r', dble(sn1))
  call print_scalar('sn1i', dimag(sn1))
  call end_test()

  ! Test 2: Real off-diagonal (b is real)
  a = dcmplx(2.0d0, 0.0d0)
  b = dcmplx(3.0d0, 0.0d0)
  c = dcmplx(5.0d0, 0.0d0)
  call zlaev2(a, b, c, rt1, rt2, cs1, sn1)
  call begin_test('real_offdiag')
  call print_scalar('ar', dble(a))
  call print_scalar('ai', dimag(a))
  call print_scalar('br', dble(b))
  call print_scalar('bi', dimag(b))
  call print_scalar('cr', dble(c))
  call print_scalar('ci', dimag(c))
  call print_scalar('rt1', rt1)
  call print_scalar('rt2', rt2)
  call print_scalar('cs1', cs1)
  call print_scalar('sn1r', dble(sn1))
  call print_scalar('sn1i', dimag(sn1))
  call end_test()

  ! Test 3: Pure imaginary b
  a = dcmplx(4.0d0, 0.0d0)
  b = dcmplx(0.0d0, 2.0d0)
  c = dcmplx(1.0d0, 0.0d0)
  call zlaev2(a, b, c, rt1, rt2, cs1, sn1)
  call begin_test('imag_b')
  call print_scalar('ar', dble(a))
  call print_scalar('ai', dimag(a))
  call print_scalar('br', dble(b))
  call print_scalar('bi', dimag(b))
  call print_scalar('cr', dble(c))
  call print_scalar('ci', dimag(c))
  call print_scalar('rt1', rt1)
  call print_scalar('rt2', rt2)
  call print_scalar('cs1', cs1)
  call print_scalar('sn1r', dble(sn1))
  call print_scalar('sn1i', dimag(sn1))
  call end_test()

  ! Test 4: Complex b (general case)
  a = dcmplx(5.0d0, 0.0d0)
  b = dcmplx(1.0d0, 2.0d0)
  c = dcmplx(3.0d0, 0.0d0)
  call zlaev2(a, b, c, rt1, rt2, cs1, sn1)
  call begin_test('complex_b')
  call print_scalar('ar', dble(a))
  call print_scalar('ai', dimag(a))
  call print_scalar('br', dble(b))
  call print_scalar('bi', dimag(b))
  call print_scalar('cr', dble(c))
  call print_scalar('ci', dimag(c))
  call print_scalar('rt1', rt1)
  call print_scalar('rt2', rt2)
  call print_scalar('cs1', cs1)
  call print_scalar('sn1r', dble(sn1))
  call print_scalar('sn1i', dimag(sn1))
  call end_test()

  ! Test 5: Identity matrix (a=c=1, b=0)
  a = dcmplx(1.0d0, 0.0d0)
  b = dcmplx(0.0d0, 0.0d0)
  c = dcmplx(1.0d0, 0.0d0)
  call zlaev2(a, b, c, rt1, rt2, cs1, sn1)
  call begin_test('identity')
  call print_scalar('ar', dble(a))
  call print_scalar('ai', dimag(a))
  call print_scalar('br', dble(b))
  call print_scalar('bi', dimag(b))
  call print_scalar('cr', dble(c))
  call print_scalar('ci', dimag(c))
  call print_scalar('rt1', rt1)
  call print_scalar('rt2', rt2)
  call print_scalar('cs1', cs1)
  call print_scalar('sn1r', dble(sn1))
  call print_scalar('sn1i', dimag(sn1))
  call end_test()

  ! Test 6: Negative diagonal with complex b
  a = dcmplx(-2.0d0, 0.0d0)
  b = dcmplx(1.0d0, -1.0d0)
  c = dcmplx(-5.0d0, 0.0d0)
  call zlaev2(a, b, c, rt1, rt2, cs1, sn1)
  call begin_test('negative_diag')
  call print_scalar('ar', dble(a))
  call print_scalar('ai', dimag(a))
  call print_scalar('br', dble(b))
  call print_scalar('bi', dimag(b))
  call print_scalar('cr', dble(c))
  call print_scalar('ci', dimag(c))
  call print_scalar('rt1', rt1)
  call print_scalar('rt2', rt2)
  call print_scalar('cs1', cs1)
  call print_scalar('sn1r', dble(sn1))
  call print_scalar('sn1i', dimag(sn1))
  call end_test()

  ! Test 7: sm = 0 path (a = -c)
  a = dcmplx(3.0d0, 0.0d0)
  b = dcmplx(2.0d0, 1.0d0)
  c = dcmplx(-3.0d0, 0.0d0)
  call zlaev2(a, b, c, rt1, rt2, cs1, sn1)
  call begin_test('sm_zero')
  call print_scalar('ar', dble(a))
  call print_scalar('ai', dimag(a))
  call print_scalar('br', dble(b))
  call print_scalar('bi', dimag(b))
  call print_scalar('cr', dble(c))
  call print_scalar('ci', dimag(c))
  call print_scalar('rt1', rt1)
  call print_scalar('rt2', rt2)
  call print_scalar('cs1', cs1)
  call print_scalar('sn1r', dble(sn1))
  call print_scalar('sn1i', dimag(sn1))
  call end_test()

  ! Test 8: Equal diagonal with complex b
  a = dcmplx(4.0d0, 0.0d0)
  b = dcmplx(3.0d0, 4.0d0)
  c = dcmplx(4.0d0, 0.0d0)
  call zlaev2(a, b, c, rt1, rt2, cs1, sn1)
  call begin_test('equal_diag')
  call print_scalar('ar', dble(a))
  call print_scalar('ai', dimag(a))
  call print_scalar('br', dble(b))
  call print_scalar('bi', dimag(b))
  call print_scalar('cr', dble(c))
  call print_scalar('ci', dimag(c))
  call print_scalar('rt1', rt1)
  call print_scalar('rt2', rt2)
  call print_scalar('cs1', cs1)
  call print_scalar('sn1r', dble(sn1))
  call print_scalar('sn1i', dimag(sn1))
  call end_test()

  ! Test 9: Large values
  a = dcmplx(1.0d10, 0.0d0)
  b = dcmplx(5.0d9, 5.0d9)
  c = dcmplx(2.0d10, 0.0d0)
  call zlaev2(a, b, c, rt1, rt2, cs1, sn1)
  call begin_test('large_values')
  call print_scalar('ar', dble(a))
  call print_scalar('ai', dimag(a))
  call print_scalar('br', dble(b))
  call print_scalar('bi', dimag(b))
  call print_scalar('cr', dble(c))
  call print_scalar('ci', dimag(c))
  call print_scalar('rt1', rt1)
  call print_scalar('rt2', rt2)
  call print_scalar('cs1', cs1)
  call print_scalar('sn1r', dble(sn1))
  call print_scalar('sn1i', dimag(sn1))
  call end_test()

  ! Test 10: a < c with complex b (df < 0)
  a = dcmplx(1.0d0, 0.0d0)
  b = dcmplx(2.0d0, -3.0d0)
  c = dcmplx(7.0d0, 0.0d0)
  call zlaev2(a, b, c, rt1, rt2, cs1, sn1)
  call begin_test('df_negative')
  call print_scalar('ar', dble(a))
  call print_scalar('ai', dimag(a))
  call print_scalar('br', dble(b))
  call print_scalar('bi', dimag(b))
  call print_scalar('cr', dble(c))
  call print_scalar('ci', dimag(c))
  call print_scalar('rt1', rt1)
  call print_scalar('rt2', rt2)
  call print_scalar('cs1', cs1)
  call print_scalar('sn1r', dble(sn1))
  call print_scalar('sn1i', dimag(sn1))
  call end_test()

end program
