/* eslint-disable no-restricted-syntax, stdlib/first-unit-test */

'use strict';

var test = require( 'node:test' );
var assert = require( 'node:assert/strict' );
var Complex128Array = require( '@stdlib/array/complex128' );
var reinterpret = require( '@stdlib/strided/base/reinterpret-complex128' );
var zggev = require( '../lib/base.js' );

// Load fixture

// FIXTURES //

var n_eq_1 = require( './fixtures/n_eq_1.json' );
var right_evec_3x3 = require( './fixtures/right_evec_3x3.json' );
var both_evec_3x3 = require( './fixtures/both_evec_3x3.json' );
var eig_only_3x3 = require( './fixtures/eig_only_3x3.json' );
var diagonal_2x2 = require( './fixtures/diagonal_2x2.json' );
var n_eq_1_noevec = require( './fixtures/n_eq_1_noevec.json' );
var left_evec_2x2 = require( './fixtures/left_evec_2x2.json' );
/**
* Assert that two floating-point numbers are close.
*/
function assertClose( actual, expected, tol, msg ) {
	var relErr;
	if ( expected === 0.0 ) {
		assert.ok( Math.abs( actual ) <= tol, msg + ': expected 0, got ' + actual );
		return;
	}
	relErr = Math.abs( actual - expected ) / Math.max( Math.abs( expected ), 1.0 );
	assert.ok( relErr <= tol, msg + ': expected ' + expected + ', got ' + actual + ' (relErr=' + relErr + ')' ); // eslint-disable-line max-len
}

/**
* Assert that two complex arrays are close, element by element.
* Operates on a Float64 view of the complex array.
*/
function assertComplexArrayClose( actual, offsetActual, expected, tol, msg ) {
	var i;
	for ( i = 0; i < expected.length; i++ ) {
		assertClose( actual[ offsetActual + i ], expected[ i ], tol, msg + '[' + i + ']' ); // eslint-disable-line max-len
	}
}

test( 'zggev: N=0 quick return', function t() {
	var ALPHA;
	var BETA;
	var info;
	var VL;
	var VR;
	var A;
	var B;

	ALPHA = new Complex128Array( 1 );
	BETA = new Complex128Array( 1 );
	VL = new Complex128Array( 1 );
	VR = new Complex128Array( 1 );
	A = new Complex128Array( 1 );
	B = new Complex128Array( 1 );
	info = zggev( 'none', 'none', 0, A, 1, 1, 0, B, 1, 1, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, 1, 0, VR, 1, 1, 0);
	assert.strictEqual( info, 0 );
});

test( 'zggev: N=1 with eigenvectors', function t() {
	var ALPHAv;
	var ALPHA;
	var BETAv;
	var BETA;
	var info;
	var LDA;
	var VLv;
	var VRv;
	var tol;
	var tc;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	tc = n_eq_1;
	N = 1;
	LDA = N;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	ALPHAv = reinterpret( ALPHA, 0 );
	BETAv = reinterpret( BETA, 0 );
	VLv = reinterpret( VL, 0 );
	VRv = reinterpret( VR, 0 );
	tol = 1e-13;
	Av[ 0 ] = 3.0;
	Av[ 1 ] = 1.0;
	Bv[ 0 ] = 2.0;
	Bv[ 1 ] = 0.5;
	info = zggev( 'compute', 'compute', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, tc.info );
	assertComplexArrayClose( ALPHAv, 0, tc.alpha, tol, 'alpha' );
	assertComplexArrayClose( BETAv, 0, tc.beta, tol, 'beta' );
	assertComplexArrayClose( VLv, 0, tc.VL, tol, 'VL' );
	assertComplexArrayClose( VRv, 0, tc.VR, tol, 'VR' );
});

test( 'zggev: 3x3 right eigenvectors only', function t() {
	var ALPHAv;
	var ALPHA;
	var BETAv;
	var BETA;
	var info;
	var LDA;
	var VRv;
	var tol;
	var tc;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	tc = right_evec_3x3;
	N = 3;
	LDA = N;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	ALPHAv = reinterpret( ALPHA, 0 );
	BETAv = reinterpret( BETA, 0 );
	VRv = reinterpret( VR, 0 );
	tol = 1e-12;
	Av[ 0 ] = 2.0;
	Av[ 1 ] = 1.0;
	Av[ 2 ] = 1.0;
	Av[ 3 ] = -1.0;
	Av[ 4 ] = 0.5;
	Av[ 5 ] = 0.5;
	Av[ 6 ] = 1.0;
	Av[ 7 ] = 0.5;
	Av[ 8 ] = 3.0;
	Av[ 9 ] = 0.0;
	Av[ 10 ] = 0.5;
	Av[ 11 ] = -0.5;
	Av[ 12 ] = 0.5;
	Av[ 13 ] = -0.5;
	Av[ 14 ] = 1.0;
	Av[ 15 ] = 1.0;
	Av[ 16 ] = 4.0;
	Av[ 17 ] = -1.0;
	Bv[ 0 ] = 3.0;
	Bv[ 1 ] = 0.0;
	Bv[ 2 ] = 0.5;
	Bv[ 3 ] = -0.5;
	Bv[ 4 ] = 0.0;
	Bv[ 5 ] = 0.5;
	Bv[ 6 ] = 1.0;
	Bv[ 7 ] = 0.5;
	Bv[ 8 ] = 2.0;
	Bv[ 9 ] = 1.0;
	Bv[ 10 ] = 0.5;
	Bv[ 11 ] = 0.0;
	Bv[ 12 ] = 0.5;
	Bv[ 13 ] = 0.5;
	Bv[ 14 ] = 1.0;
	Bv[ 15 ] = 0.0;
	Bv[ 16 ] = 1.0;
	Bv[ 17 ] = 0.5;
	info = zggev( 'none', 'compute', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, tc.info );
	assertComplexArrayClose( ALPHAv, 0, tc.alpha, tol, 'alpha' );
	assertComplexArrayClose( BETAv, 0, tc.beta, tol, 'beta' );
	assertComplexArrayClose( VRv, 0, tc.VR_col1, tol, 'VR_col1' );
	assertComplexArrayClose( VRv, 2 * N, tc.VR_col2, tol, 'VR_col2' );
	assertComplexArrayClose( VRv, 4 * N, tc.VR_col3, tol, 'VR_col3' );
});

test( 'zggev: 3x3 both eigenvectors', function t() {
	var ALPHAv;
	var ALPHA;
	var BETAv;
	var BETA;
	var info;
	var LDA;
	var VLv;
	var VRv;
	var tol;
	var tc;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	tc = both_evec_3x3;
	N = 3;
	LDA = N;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	ALPHAv = reinterpret( ALPHA, 0 );
	BETAv = reinterpret( BETA, 0 );
	VLv = reinterpret( VL, 0 );
	VRv = reinterpret( VR, 0 );
	tol = 1e-12;
	Av[ 0 ] = 2.0;
	Av[ 1 ] = 1.0;
	Av[ 2 ] = 1.0;
	Av[ 3 ] = -1.0;
	Av[ 4 ] = 0.5;
	Av[ 5 ] = 0.5;
	Av[ 6 ] = 1.0;
	Av[ 7 ] = 0.5;
	Av[ 8 ] = 3.0;
	Av[ 9 ] = 0.0;
	Av[ 10 ] = 0.5;
	Av[ 11 ] = -0.5;
	Av[ 12 ] = 0.5;
	Av[ 13 ] = -0.5;
	Av[ 14 ] = 1.0;
	Av[ 15 ] = 1.0;
	Av[ 16 ] = 4.0;
	Av[ 17 ] = -1.0;
	Bv[ 0 ] = 3.0;
	Bv[ 1 ] = 0.0;
	Bv[ 2 ] = 0.5;
	Bv[ 3 ] = -0.5;
	Bv[ 4 ] = 0.0;
	Bv[ 5 ] = 0.5;
	Bv[ 6 ] = 1.0;
	Bv[ 7 ] = 0.5;
	Bv[ 8 ] = 2.0;
	Bv[ 9 ] = 1.0;
	Bv[ 10 ] = 0.5;
	Bv[ 11 ] = 0.0;
	Bv[ 12 ] = 0.5;
	Bv[ 13 ] = 0.5;
	Bv[ 14 ] = 1.0;
	Bv[ 15 ] = 0.0;
	Bv[ 16 ] = 1.0;
	Bv[ 17 ] = 0.5;
	info = zggev( 'compute', 'compute', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, tc.info );
	assertComplexArrayClose( ALPHAv, 0, tc.alpha, tol, 'alpha' );
	assertComplexArrayClose( BETAv, 0, tc.beta, tol, 'beta' );
	assertComplexArrayClose( VLv, 0, tc.VL_col1, tol, 'VL_col1' );
	assertComplexArrayClose( VLv, 2 * N, tc.VL_col2, tol, 'VL_col2' );
	assertComplexArrayClose( VLv, 4 * N, tc.VL_col3, tol, 'VL_col3' );
	assertComplexArrayClose( VRv, 0, tc.VR_col1, tol, 'VR_col1' );
	assertComplexArrayClose( VRv, 2 * N, tc.VR_col2, tol, 'VR_col2' );
	assertComplexArrayClose( VRv, 4 * N, tc.VR_col3, tol, 'VR_col3' );
});

test( 'zggev: 3x3 eigenvalues only', function t() {
	var ALPHAv;
	var ALPHA;
	var BETAv;
	var BETA;
	var info;
	var LDA;
	var tol;
	var tc;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	tc = eig_only_3x3;
	N = 3;
	LDA = N;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	ALPHAv = reinterpret( ALPHA, 0 );
	BETAv = reinterpret( BETA, 0 );
	tol = 1e-12;
	Av[ 0 ] = 2.0;
	Av[ 1 ] = 1.0;
	Av[ 2 ] = 1.0;
	Av[ 3 ] = -1.0;
	Av[ 4 ] = 0.5;
	Av[ 5 ] = 0.5;
	Av[ 6 ] = 1.0;
	Av[ 7 ] = 0.5;
	Av[ 8 ] = 3.0;
	Av[ 9 ] = 0.0;
	Av[ 10 ] = 0.5;
	Av[ 11 ] = -0.5;
	Av[ 12 ] = 0.5;
	Av[ 13 ] = -0.5;
	Av[ 14 ] = 1.0;
	Av[ 15 ] = 1.0;
	Av[ 16 ] = 4.0;
	Av[ 17 ] = -1.0;
	Bv[ 0 ] = 3.0;
	Bv[ 1 ] = 0.0;
	Bv[ 2 ] = 0.5;
	Bv[ 3 ] = -0.5;
	Bv[ 4 ] = 0.0;
	Bv[ 5 ] = 0.5;
	Bv[ 6 ] = 1.0;
	Bv[ 7 ] = 0.5;
	Bv[ 8 ] = 2.0;
	Bv[ 9 ] = 1.0;
	Bv[ 10 ] = 0.5;
	Bv[ 11 ] = 0.0;
	Bv[ 12 ] = 0.5;
	Bv[ 13 ] = 0.5;
	Bv[ 14 ] = 1.0;
	Bv[ 15 ] = 0.0;
	Bv[ 16 ] = 1.0;
	Bv[ 17 ] = 0.5;
	info = zggev( 'none', 'none', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, tc.info );
	assertComplexArrayClose( ALPHAv, 0, tc.alpha, tol, 'alpha' );
	assertComplexArrayClose( BETAv, 0, tc.beta, tol, 'beta' );
});

test( 'zggev: 2x2 diagonal', function t() {
	var ALPHAv;
	var ALPHA;
	var BETAv;
	var BETA;
	var info;
	var LDA;
	var VLv;
	var VRv;
	var tol;
	var tc;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	tc = diagonal_2x2;
	N = 2;
	LDA = N;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	ALPHAv = reinterpret( ALPHA, 0 );
	BETAv = reinterpret( BETA, 0 );
	VLv = reinterpret( VL, 0 );
	VRv = reinterpret( VR, 0 );
	tol = 1e-13;
	Av[ 0 ] = 4.0;
	Av[ 1 ] = 0.0;
	Av[ 2 ] = 0.0;
	Av[ 3 ] = 0.0;
	Av[ 4 ] = 0.0;
	Av[ 5 ] = 0.0;
	Av[ 6 ] = 6.0;
	Av[ 7 ] = 0.0;
	Bv[ 0 ] = 2.0;
	Bv[ 1 ] = 0.0;
	Bv[ 2 ] = 0.0;
	Bv[ 3 ] = 0.0;
	Bv[ 4 ] = 0.0;
	Bv[ 5 ] = 0.0;
	Bv[ 6 ] = 3.0;
	Bv[ 7 ] = 0.0;
	info = zggev( 'compute', 'compute', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, tc.info );
	assertComplexArrayClose( ALPHAv, 0, tc.alpha, tol, 'alpha' );
	assertComplexArrayClose( BETAv, 0, tc.beta, tol, 'beta' );
	assertComplexArrayClose( VLv, 0, tc.VL_col1, tol, 'VL_col1' );
	assertComplexArrayClose( VLv, 2 * N, tc.VL_col2, tol, 'VL_col2' );
	assertComplexArrayClose( VRv, 0, tc.VR_col1, tol, 'VR_col1' );
	assertComplexArrayClose( VRv, 2 * N, tc.VR_col2, tol, 'VR_col2' );
});

test( 'zggev: N=1 no eigenvectors', function t() {
	var ALPHAv;
	var ALPHA;
	var BETAv;
	var BETA;
	var info;
	var LDA;
	var tol;
	var tc;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	tc = n_eq_1_noevec;
	N = 1;
	LDA = N;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	ALPHAv = reinterpret( ALPHA, 0 );
	BETAv = reinterpret( BETA, 0 );
	tol = 1e-13;
	Av[ 0 ] = 5.0;
	Av[ 1 ] = 2.0;
	Bv[ 0 ] = 1.0;
	Bv[ 1 ] = 0.0;
	info = zggev( 'none', 'none', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, tc.info );
	assertComplexArrayClose( ALPHAv, 0, tc.alpha, tol, 'alpha' );
	assertComplexArrayClose( BETAv, 0, tc.beta, tol, 'beta' );
});

test( 'zggev: 2x2 left eigenvectors only', function t() {
	var ALPHAv;
	var ALPHA;
	var BETAv;
	var BETA;
	var info;
	var LDA;
	var VLv;
	var tol;
	var tc;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	tc = left_evec_2x2;
	N = 2;
	LDA = N;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	ALPHAv = reinterpret( ALPHA, 0 );
	BETAv = reinterpret( BETA, 0 );
	VLv = reinterpret( VL, 0 );
	tol = 1e-12;
	Av[ 0 ] = 1.0;
	Av[ 1 ] = 2.0;
	Av[ 2 ] = 0.5;
	Av[ 3 ] = 0.5;
	Av[ 4 ] = 3.0;
	Av[ 5 ] = -1.0;
	Av[ 6 ] = 4.0;
	Av[ 7 ] = 1.0;
	Bv[ 0 ] = 2.0;
	Bv[ 1 ] = 0.0;
	Bv[ 2 ] = 0.0;
	Bv[ 3 ] = 0.0;
	Bv[ 4 ] = 1.0;
	Bv[ 5 ] = 1.0;
	Bv[ 6 ] = 3.0;
	Bv[ 7 ] = -0.5;
	info = zggev( 'compute', 'none', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, tc.info );
	assertComplexArrayClose( ALPHAv, 0, tc.alpha, tol, 'alpha' );
	assertComplexArrayClose( BETAv, 0, tc.beta, tol, 'beta' );
	assertComplexArrayClose( VLv, 0, tc.VL_col1, tol, 'VL_col1' );
	assertComplexArrayClose( VLv, 2 * N, tc.VL_col2, tol, 'VL_col2' );
});

test( 'zggev: small entries trigger anrm < smlnum scaling', function t() {
	var ALPHAv;
	var scale;
	var ALPHA;
	var BETAv;
	var BETA;
	var info;
	var LDA;
	var tol;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	N = 2;
	LDA = N;
	scale = 1e-300;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	ALPHAv = reinterpret( ALPHA, 0 );
	BETAv = reinterpret( BETA, 0 );
	tol = 1e-10;
	Av[ 0 ] = 4.0 * scale;
	Av[ 1 ] = 0.0;
	Av[ 2 ] = 0.0;
	Av[ 3 ] = 0.0;
	Av[ 4 ] = 0.0;
	Av[ 5 ] = 0.0;
	Av[ 6 ] = 6.0 * scale;
	Av[ 7 ] = 0.0;
	Bv[ 0 ] = 2.0 * scale;
	Bv[ 1 ] = 0.0;
	Bv[ 2 ] = 0.0;
	Bv[ 3 ] = 0.0;
	Bv[ 4 ] = 0.0;
	Bv[ 5 ] = 0.0;
	Bv[ 6 ] = 3.0 * scale;
	Bv[ 7 ] = 0.0;
	info = zggev( 'none', 'none', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, 0, 'info' );
	assertClose( ALPHAv[0] / BETAv[0], 2.0, tol, 'eigenvalue 0 ratio' );
	assertClose( ALPHAv[2] / BETAv[2], 2.0, tol, 'eigenvalue 1 ratio' );
});

test( 'zggev: large entries trigger anrm > bignum scaling', function t() {
	var ALPHAv;
	var scale;
	var ALPHA;
	var BETAv;
	var BETA;
	var info;
	var LDA;
	var tol;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	N = 2;
	LDA = N;
	scale = 1e+300;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	ALPHAv = reinterpret( ALPHA, 0 );
	BETAv = reinterpret( BETA, 0 );
	tol = 1e-10;
	Av[ 0 ] = 4.0 * scale;
	Av[ 1 ] = 0.0;
	Av[ 2 ] = 0.0;
	Av[ 3 ] = 0.0;
	Av[ 4 ] = 0.0;
	Av[ 5 ] = 0.0;
	Av[ 6 ] = 6.0 * scale;
	Av[ 7 ] = 0.0;
	Bv[ 0 ] = 2.0 * scale;
	Bv[ 1 ] = 0.0;
	Bv[ 2 ] = 0.0;
	Bv[ 3 ] = 0.0;
	Bv[ 4 ] = 0.0;
	Bv[ 5 ] = 0.0;
	Bv[ 6 ] = 3.0 * scale;
	Bv[ 7 ] = 0.0;
	info = zggev( 'none', 'none', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, 0, 'info' );
	assertClose( ALPHAv[0] / BETAv[0], 2.0, tol, 'eigenvalue 0 ratio' );
	assertClose( ALPHAv[2] / BETAv[2], 2.0, tol, 'eigenvalue 1 ratio' );
});

test( 'zggev: small B entries trigger bnrm < smlnum scaling', function t() {
	var scale;
	var ALPHA;
	var BETA;
	var info;
	var LDA;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	N = 2;
	LDA = N;
	scale = 1e-300;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	Av[ 0 ] = 4.0;
	Av[ 1 ] = 0.0;
	Av[ 2 ] = 0.0;
	Av[ 3 ] = 0.0;
	Av[ 4 ] = 0.0;
	Av[ 5 ] = 0.0;
	Av[ 6 ] = 6.0;
	Av[ 7 ] = 0.0;
	Bv[ 0 ] = 2.0 * scale;
	Bv[ 1 ] = 0.0;
	Bv[ 2 ] = 0.0;
	Bv[ 3 ] = 0.0;
	Bv[ 4 ] = 0.0;
	Bv[ 5 ] = 0.0;
	Bv[ 6 ] = 3.0 * scale;
	Bv[ 7 ] = 0.0;
	info = zggev( 'none', 'none', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, 0, 'info' );
});

test( 'zggev: large B entries trigger bnrm > bignum scaling', function t() {
	var scale;
	var ALPHA;
	var BETA;
	var info;
	var LDA;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	N = 2;
	LDA = N;
	scale = 1e+300;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	Av[ 0 ] = 4.0;
	Av[ 1 ] = 0.0;
	Av[ 2 ] = 0.0;
	Av[ 3 ] = 0.0;
	Av[ 4 ] = 0.0;
	Av[ 5 ] = 0.0;
	Av[ 6 ] = 6.0;
	Av[ 7 ] = 0.0;
	Bv[ 0 ] = 2.0 * scale;
	Bv[ 1 ] = 0.0;
	Bv[ 2 ] = 0.0;
	Bv[ 3 ] = 0.0;
	Bv[ 4 ] = 0.0;
	Bv[ 5 ] = 0.0;
	Bv[ 6 ] = 3.0 * scale;
	Bv[ 7 ] = 0.0;
	info = zggev( 'none', 'none', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, 0, 'info' );
});

test( 'zggev: both A and B scaled (small A, large B) with eigenvectors', function t() { // eslint-disable-line max-len
	var ALPHAv;
	var ALPHA;
	var BETAv;
	var BETA;
	var info;
	var LDA;
	var tol;
	var VL;
	var VR;
	var Av;
	var Bv;
	var N;
	var A;
	var B;

	N = 2;
	LDA = N;
	A = new Complex128Array( LDA * N );
	B = new Complex128Array( LDA * N );
	ALPHA = new Complex128Array( N );
	BETA = new Complex128Array( N );
	VL = new Complex128Array( N * N );
	VR = new Complex128Array( N * N );
	Av = reinterpret( A, 0 );
	Bv = reinterpret( B, 0 );
	ALPHAv = reinterpret( ALPHA, 0 );
	BETAv = reinterpret( BETA, 0 );
	tol = 1e-8;
	Av[ 0 ] = 1e-300;
	Av[ 1 ] = 0.0;
	Av[ 2 ] = 0.0;
	Av[ 3 ] = 0.0;
	Av[ 4 ] = 0.0;
	Av[ 5 ] = 0.0;
	Av[ 6 ] = 2e-300;
	Av[ 7 ] = 0.0;
	Bv[ 0 ] = 1e+300;
	Bv[ 1 ] = 0.0;
	Bv[ 2 ] = 0.0;
	Bv[ 3 ] = 0.0;
	Bv[ 4 ] = 0.0;
	Bv[ 5 ] = 0.0;
	Bv[ 6 ] = 1e+300;
	Bv[ 7 ] = 0.0;
	info = zggev( 'compute', 'compute', N, A, 1, LDA, 0, B, 1, LDA, 0, ALPHA, 1, 0, BETA, 1, 0, VL, 1, N, 0, VR, 1, N, 0);
	assert.strictEqual( info, 0, 'info' );
	assert.ok( isFinite( ALPHAv[0] ), 'alpha[0] is finite' );
	assert.ok( isFinite( BETAv[0] ), 'beta[0] is finite' );
});
